[versions]
agp = "8.5.2"
kotlin = "1.9.24"
composeBom = "2024.10.01"
activityCompose = "1.9.3"
navigationCompose = "2.8.4"
lifecycleRuntimeKtx = "2.8.7"
room = "2.6.1"
ksp = "1.9.24-1.0.20"
sqlcipher = "4.5.4"
sqliteX = "2.4.0"
securityCrypto = "1.1.0-alpha06"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }

androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqliteX" }

androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
